### Instruction

1. X.Y: X means the chapter number, and Y means the subsection number of this chapter, and if there's another number, which means more than 1 question.
2. To facilitate quick retrieval, you may click on each heading to collapse the questions.




In [1]:
import math
import numpy as np

### 9.1 Basic NumPy Usage

1. Write your own logarithm function that will compute the logarithm of a number to any given positive base, *i.e.* it should take two inputs, the value to be logged and the base.

In [5]:
def log_function(a,b):
    result=np.log(b)/np.log(a) # a as the base
    return result
    
log_input = log_function(1.2,5)
log_input

np.float64(8.827469119589406)

2. Write your own trigonometric functions that use the NumPy functions but that work with degrees instead of radians.

In [3]:
def trig_func(degrees):
    radians=degrees*math.pi/180
    sin_result=np.sin(radians)
    cos_result=np.cos(radians)
    tan_result=np.tan(radians)
    return sin_result,cos_result,tan_result

sin_val, cos_val, tan_val = trig_func(123)
print("The sin value is: ",sin_val)
print("The cos value is: ",cos_val)
print("The tan value is: ",tan_val)

The sin value is:  0.838670567945424
The cos value is:  -0.5446390350150272
The tan value is:  -1.539864963814583


### 9.2 Creating Vectors in NumPy

1. Use the `np.array()` function to create an array with the entries 2, 4, 6, 8 and 10 in it.

In [41]:
np.array([2,4,6,8,10])

array([ 2,  4,  6,  8, 10])

2. Use the `np.array()` function to create an array with complex numbers `1+i`, `2+2i`, `3+3i`, `4+4i` in it.

In [40]:
np.array([1+1j,2+2j,3+3j,4+4j])
# There must be a number before 'j'
# j is Python's native imaginary unit symbol.

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

3. Use `np.zeros()` to create a vector of zeros of length 10.

In [39]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

4. Use `np.linspace()` to create a vector of length 15 between `a=5` and `b=19`.

In [38]:
np.linspace(5,19,15)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
       18., 19.])

5. Use `np.logspace()` to create a vector of length 10 between $10^{-9}$ and $10^0$. 

In [6]:
np.logspace(-9,0,10)

array([1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02,
       1.e-01, 1.e+00])

### 9.3 Working with Vectors

1. Use `np.zeros()` to create a vector of length 4.
    - Manually fill the 0th and 2nd entries with the value 2 and 4, respectively.
    - What happens if you try and fill entry 1 with a complex number?
    - Instead, use the syntax `np.zeros(4,complex)` to set the array up. Can you use complex numbers now? 

In [19]:
vec = np.zeros(4)
vec[0] = 3
vec[2] = 4
new_vec = np.zeros(4,complex)
new_vec[1] = 2+3j
print(vec)
print(new_vec)

[3. 0. 4. 0.]
[0.+0.j 2.+3.j 0.+0.j 0.+0.j]



2. Use `np.linspace()` to set up a vector containing the first 10 natural numbers.
    - Use slicing to extract the odd valued natural numbers as an array.
    - Use slicing to extract the even valued natural numbers as an array.
    - Use slicing to extract an array of the even natural numbers but counting backwards from 10.

3. Investigate the use of `np.sum()` and `np.prod()` applied to a NumPy array.

4. Write a function that will find the angle between 2 vectors. These vectors should be of length $2$ or $3$ and your code should check that this is the case and give appropriate error messages if not.